<link href="<%=path%>/static/css/bootstrap.min.css" rel="stylesheet">
<link href="<%=path%>/static/css/font-awesome.min.css" rel="stylesheet">
<link href="<%=path%>/static/css/animate.css" rel="stylesheet">
<link href="<%=path%>/static/css/style.css" rel="stylesheet">
<link href="<%=path%>/static/css/plugins/select2/select2.min.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/plugins/select2/select2-bootstrap.min.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/plugins/bootstrap-table/bootstrap-table.min.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/plugins/sweetalert/sweetalert2.min.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/plugins/iCheck/skins/all.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/plugins/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/plugins/bootstrapValidator/bootstrapValidator.min.css" rel="stylesheet"/>
<link href="<%=path%>/static/css/site-main.css" rel="stylesheet"/>